### ISSUE TITLE
Error while connecting https: SSL_ERROR_NO_CYPHER_OVERLAP

### ISSUE THREAD

**Issue by phatillo** [kvic-z/pixelserv-tls#3] opened 2017-11-02 21:46 UTC
While http part of the pixelserv is working perfectly, trying to connect to https port raises an error SSL_ERROR_NO_CYPHER_OVERLAP in Firefox 51. Does pixelserv support modern ciphers?

**Comment by kvic-z** [comment] 2017-11-03 07:44
I couldn't reproduce with Firefox 56. Did you override TLS setting in your Firefox?

pixelserv-tls currently supports TLSv1.2.

**Comment by phatillo** [comment] 2017-11-03 07:50
No, I have changed nothing. The Firefox is of default installation. Yeah, Firefox is under Windows 7 x64, while the pixelserv runs under Debian 9 x64; the static build because libssl in the system is 1.0.2.

**Comment by kvic-z** [comment] 2017-11-04 10:34
I spent more time on this, and still couldn't reproduce the error.

However, my Linux VM is Debian 8. Tried both static and dynamic of Kk and Kl-test4. For the dynamic version, also tried with openssl 1.0.2 libs.

Had it ever worked for you before or you just started recently? What was the CLI you generated the CA certificate?

**Comment by MrT69** [comment] 2017-11-04 14:17
@phatillo
Can you let me know your current configuration? How do you use the Pixelserver?
Can you post the CA (without Public Key) to reproduce the error?

**Comment by kvic-z** [comment] 2017-11-15 02:15
SSL_ERROR_NO_CYPHER_OVERLAP can be reproduced in recent version of Chrome and Firefox when accessing pixelserv-tls by its IPv4 address.

This issue will be fixed in the coming KL-test4 for tests.

**Comment by MrT69** [comment] 2017-11-15 04:50
This error could also happens after several updates. Than it is necessary to delete the Cert8.db and rebuild it. All personal Certs will be lost after delete this file so it is important to export them bevore you delete this file.

How ti:

http://kb.mit.edu/confluence/display/istcontrib/Deleting+Cert8.db+for+Firefox

**Comment by kvic-z** [comment] 2017-11-27 18:32
Closed the issue with inactivity from OP.

**Closed by kvic-z** 2017-11-27 18:32 UTC
